services:
  app:
    build: .
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:17-alpine
    ports:
      - '5434:5432'
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
